### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by paulswithers** [OpenNTF/das-api-specs#12]
Could you confirm if the repo is still active and needed? To do so, just close this issue by end of Feb 2024. If not, we'll archive the repo. The repo can still be unarchived, so it's not a destructive action.

**Comment by ddelay** [comment]
I don't think this repo is active, but I am retired from HCL. It's not up to me. You might want to contact someone at HCL (perhaps @hcldan) before archiving. 

I'll leave the issue open for now. Let me know if I should close it.

**Comment by hcldan** [comment]
@paulswithers please avoid archiving this.  The owner will likely need to move to someone still employed at HCL (you can assign to me for now).

These apis are still in Domino, so I think the specs here should be kept available.

**Comment by paulswithers** [comment]
Done
